"""add_new_consultation_statuses

Revision ID: 231512c8a0b3
Revises: 0fbf9f2170bc
Create Date: 2025-08-17 17:06:10.741457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231512c8a0b3'
down_revision: Union[str, Sequence[str], None] = '0fbf9f2170bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
