"""add new consultation status enum values

Revision ID: 2e3a6f4f74bc
Revises: abdd8fdf323b
Create Date: 2025-08-19 16:24:56.495254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e3a6f4f74bc'
down_revision: Union[str, Sequence[str], None] = 'abdd8fdf323b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_consultation_buffer_consultation'), table_name='consultation_buffer')
    op.drop_index(op.f('idx_consultation_buffer_created'), table_name='consultation_buffer')
    op.alter_column('consultation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_consultations_active_client_unique'), table_name='consultations', postgresql_where="(status = ANY (ARRAY['active'::consultationstatusenum, 'pending'::consultationstatusenum]))")
    op.drop_index(op.f('idx_consultations_expires_at'), table_name='consultations', postgresql_where="((expires_at IS NOT NULL) AND (status = 'pending'::consultationstatusenum))")
    op.drop_index(op.f('idx_consultations_florist_status'), table_name='consultations', postgresql_where="(status = ANY (ARRAY['active'::consultationstatusenum, 'pending'::consultationstatusenum]))")
    op.drop_index(op.f('idx_consultations_request_key_unique'), table_name='consultations', postgresql_where='(request_key IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_consultations_request_key_unique'), 'consultations', ['request_key'], unique=True, postgresql_where='(request_key IS NOT NULL)')
    op.create_index(op.f('idx_consultations_florist_status'), 'consultations', ['florist_id', 'status'], unique=False, postgresql_where="(status = ANY (ARRAY['active'::consultationstatusenum, 'pending'::consultationstatusenum]))")
    op.create_index(op.f('idx_consultations_expires_at'), 'consultations', ['expires_at'], unique=False, postgresql_where="((expires_at IS NOT NULL) AND (status = 'pending'::consultationstatusenum))")
    op.create_index(op.f('idx_consultations_active_client_unique'), 'consultations', ['client_id'], unique=True, postgresql_where="(status = ANY (ARRAY['active'::consultationstatusenum, 'pending'::consultationstatusenum]))")
    op.alter_column('consultation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('idx_consultation_buffer_created'), 'consultation_buffer', ['created_at'], unique=False)
    op.create_index(op.f('idx_consultation_buffer_consultation'), 'consultation_buffer', ['consultation_id'], unique=False)
    # ### end Alembic commands ###
