"""add_consultation_theme_and_archive_fields

Revision ID: 726e61cee20b
Revises: 4a877086b38e
Create Date: 2025-08-12 16:22:48.162154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726e61cee20b'
down_revision: Union[str, Sequence[str], None] = '4a877086b38e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
